package net.nyohoki.tsumiki;

import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.minecraft.client.render.RenderLayer;

public class TsumikiClient implements ClientModInitializer {

    @Override
    public void onInitializeClient() {
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GURASU, RenderLayer.getTranslucent());
		// glass	
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GLASS_WALL, RenderLayer.getTranslucent());
		// white	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.WHITE_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// pink	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PINK_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// red	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.RED_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// orange	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.ORANGE_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// yellow	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.YELLOW_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// lime	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIME_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// green	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GREEN_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// cyan	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.CYAN_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// light blue	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_BLUE_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// blue	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLUE_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// purple	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.PURPLE_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// magenta	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.MAGENTA_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// brown	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BROWN_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// light gray	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.LIGHT_GRAY_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// gray	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.GRAY_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// black	
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.BLACK_STAINED_GLASS_WALL, RenderLayer.getTranslucent());
		// might need to change this
		BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_BUTTON, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_CARPET, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_DOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_FENCE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_GATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_PRESSURE_PLATE, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_SLAB, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_STAIRS, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_TRAPDOOR, RenderLayer.getTranslucent());
        BlockRenderLayerMap.INSTANCE.putBlock(Tsumiki.TINTED_GLASS_WALL, RenderLayer.getTranslucent());
		
    }
}
