package nyohoki.tsumiki;

import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.minecraft.client.render.RenderLayer;
import nyohoki.tsumiki.block.*;

import java.awt.*;

public class TsumikiClient implements ClientModInitializer {
	@Override
	public void onInitializeClient() {
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.WHITE_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.PINK_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.RED_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.ORANGE_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.YELLOW_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.LIME_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.GREEN_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.CYAN_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.LIGHT_BLUE_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.BLUE_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.PURPLE_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.MAGENTA_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.BROWN_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.LIGHT_GRAY_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.GRAY_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.BLACK_STAINED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			ButtonBlocks.TINTED_GLASS_BUTTON,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.WHITE_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.PINK_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.RED_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.ORANGE_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.YELLOW_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.LIME_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.GREEN_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.CYAN_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.LIGHT_BLUE_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.BLUE_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.PURPLE_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.MAGENTA_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.BROWN_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.LIGHT_GRAY_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.GRAY_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.BLACK_STAINED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			CarpetBlocks.TINTED_GLASS_CARPET,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.WHITE_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.PINK_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.RED_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.ORANGE_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.YELLOW_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.LIME_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.GREEN_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.CYAN_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.LIGHT_BLUE_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.BLUE_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.PURPLE_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.MAGENTA_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.BROWN_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.LIGHT_GRAY_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.GRAY_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.BLACK_STAINED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			DoorBlocks.TINTED_GLASS_DOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.WHITE_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.PINK_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.RED_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.ORANGE_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.YELLOW_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.LIME_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.GREEN_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.CYAN_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.LIGHT_BLUE_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.BLUE_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.PURPLE_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.MAGENTA_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.BROWN_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.LIGHT_GRAY_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.GRAY_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.BLACK_STAINED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			FenceBlocks.TINTED_GLASS_FENCE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.WHITE_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.PINK_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.RED_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.ORANGE_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.YELLOW_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.LIME_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.GREEN_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.CYAN_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.LIGHT_BLUE_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.BLUE_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.PURPLE_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.MAGENTA_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.BROWN_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.LIGHT_GRAY_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.GRAY_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.BLACK_STAINED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			GateBlocks.TINTED_GLASS_GATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.WHITE_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.PINK_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.RED_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.ORANGE_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.YELLOW_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.LIME_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.GREEN_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.CYAN_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.LIGHT_BLUE_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.BLUE_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.PURPLE_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.MAGENTA_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.BROWN_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.LIGHT_GRAY_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.GRAY_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.BLACK_STAINED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			PressurePlateBlocks.TINTED_GLASS_PRESSURE_PLATE,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.WHITE_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.PINK_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.RED_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.ORANGE_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.YELLOW_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.LIME_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.GREEN_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.CYAN_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.LIGHT_BLUE_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.BLUE_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.PURPLE_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.MAGENTA_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.BROWN_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.GRAY_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.BLACK_STAINED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			SlabBlocks.TINTED_GLASS_SLAB,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.WHITE_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.PINK_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.RED_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.ORANGE_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.YELLOW_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.LIME_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.GREEN_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.CYAN_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.LIGHT_BLUE_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.BLUE_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.PURPLE_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.MAGENTA_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.BROWN_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.LIGHT_GRAY_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.GRAY_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.BLACK_STAINED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			StairBlocks.TINTED_GLASS_STAIRS,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.WHITE_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.PINK_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.RED_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.ORANGE_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.YELLOW_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.LIME_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.GREEN_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.CYAN_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.LIGHT_BLUE_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.BLUE_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.PURPLE_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.MAGENTA_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.BROWN_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.LIGHT_GRAY_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.GRAY_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.BLACK_STAINED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			TrapdoorBlocks.TINTED_GLASS_TRAPDOOR,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.WHITE_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.PINK_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.RED_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.ORANGE_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.YELLOW_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.LIME_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.GREEN_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.CYAN_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.LIGHT_BLUE_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.BLUE_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.PURPLE_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.MAGENTA_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.BROWN_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.LIGHT_GRAY_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.GRAY_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.BLACK_STAINED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
		BlockRenderLayerMap.INSTANCE.putBlock(
			WallBlocks.TINTED_GLASS_WALL,
			RenderLayer.getTranslucent()
		);
	}
}
